"""Default products added when creating a new household."""

DEFAULT_PRODUCTS = [
    "Ciasto francuskie",
    "Banany",
    "Mandarynki",
    "Pomarańcze",
    "Imbir",
    "Cytryny",
    "Dynia",
    "Łosoś wędzony w plastrach",
    "Śledzie",
    "Pomidory",
    "Kabanosy",
    "Wędlina",
    "Ser żółty",
    "Łosoś świeży",
    "Serek wiejski",
    "Ser feta",
    "Serek waniliowy",
    "Twaróg",
    "Serek Almette",
    "Jogurt naturalny",
    "Serek homo",
    "Jogurt owocowy",
    "Fantazja",
    "Jogurt pitny",
    "Masło",
    "Śmietana",
    "Bułka tarta",
    "Tortilla (pizza)",
    "Wafle paprykowe",
    "Chleb",
    "Goździki",
    "Piersi z kurczaka",
    "Mięso do rosołu",
    "Frytki",
    "Ryż arborio",
    "Kasza manna",
    "Cukierki",
    "Migdały blanszowane",
    "Lubisie",
    "Herbata jakaś dobra zimowa",
    "Herbata malinowa",
    "Ziemniaki",
    "Czosnek",
    "Cebula",
    "Brokuł",
    "Warzywa do rosołu",
    "Kalafior",
    "Jabłka",
    "Gruszka",
    "Awokado",
    "Płatki corn flakes",
    "Płatki owsiane",
    "Kakao do picia dla Kacpra",
    "Śmietanka",
    "Dżem truskawkowy",
    "Dżem wiśniowy",
    "Dżem malinowy",
    "Mąka",
    "Cukier",
    "Cukier waniliowy",
    "Cukier puder",
    "Ekstrakt waniliowy",
    "Aromat migdałowy",
    "Drożdże",
    "Mleko",
    "Jajka",
    "Olej",
    "Musztarda",
    "Ketchup",
    "Pomidory w puszce",
    "Passata pomidorowa",
    "Szpinak w liściach mrożony",
    "Tuńczyk w puszce",
    "Kukurydza",
    "Ocet",
    "Makaron",
    "Papier toaletowy",
    "Ręcznik papierowy",
    "Żel do kąpieli (Sławka)",
    "Płyn do mycia naczyń",
    "Płyn do płukania",
    "Kapsułki do zmywarki",
    "Żel pod prysznic Dove",
    "Worki na śmieci",
    "Cola",
    "Sok pomarańczowy",
    "Sok jabłkowy",
    "Tubki",
    "Popcorn",
]
